[tool.poetry]
name = "app"
version = "0.0.1"
description = "Ultimate FastAPI Tutorial Part 1"
authors = ["SayfullinRR"]

[tool.poetry.dependencies]
python = "^3.8"
uvicorn = "~0.19.0"
fastapi = "~0.85.1"
python-multipart = "~0.0.5"
pydantic = {extras = ["email"], version = "~1.10.2"}