# Generated by Django 4.0.2 on 2022-02-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquerystatus',
            old_name='froze',
            new_name='inquery',
        ),
    ]
